pose:
  targets:
    bag_1:
        px: 0.843465
        py: 5.805814
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.99994
        ow: 0.01094
    bag_2:
        px: -0.4864
        py: 7.9802
        pz: 0
        ox: 0
        oy: 0
        oz: -0.9995
        ow: 0.0289
    initial_point:
        px: -0.4864
        py: 7.9802
        pz: 0
        ox: 0
        oy: 0
        oz: -0.9995
        ow: 0.0289
