pose:
  targets:
    pass:
        px: 2.9847
        py: 0.5306
        pz: 0
        ox: 0
        oy: 0
        oz: 0.0423
        ow: 0.9991
    observation:
        px: 3.64059676
        py: 2.234530
        pz: 0
        ox: 0
        oy: 0
        oz: 0.9971186
        ow: 0.0758582
    exit:
        px: -0.4864
        py: 7.9802
        pz: 0
        ox: 0
        oy: 0
        oz: -0.9995
        ow: 0.0289
