pose:
  targets:
    shelf:
        px: 35.2525
        py: 25.4061
        pz: 0
        ox: 0
        oy: 0
        oz: -0.1464
        ow: 0.9892
    exit:
        px: 38.0448
        py: 25.7673
        pz: 0
        ox: 0
        oy: 0
        oz: -0.1551
        ow: 0.9878
