pose:
  targets:
    shelf:
        px: -4.606
        py: 1.866
        pz: 0.229
        ox: 0.001
        oy: -0.002
        oz: 0.615
        ow: 0.788
    exit:
        px: 0
        py: 0
        pz: 0.229
        ox: 0
        oy: 0
        oz: 0
        ow: 1
