pose:
  targets:
    #do lado da prateleira
    kitchen:
        px: 2.916080432738566
        py: 1.1260851838404962
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.5276087859822187
        ow: 0.8494874742775018
    #collection 1
    living room:
        px: -1.37030224625324
        py: -0.4917504359244355
        pz: 0.0 
        ox: 0.0
        oy: 0.0
        oz: -0.7688201783084699
        ow: 0.7630150727467466
    #em frente a mesa verde
    bedroom:
        px: -0.6071330381293576
        py: 1.026778085437491
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: 0.9485324061003506
        ow: 0.3166800823820146
    #em frente a mesa do fsek
    entrance:
        px: 0.8792323471127507
        py: 6.780815326482573
        pz: 0.0 
        ox: 0.0
        oy: 0.0
        oz: 0.9973804946773753
        ow: 0.07233359411168547
    #em frente a mesa da impressora
    bedroom_2:
        px: 0.82012951757833
        py: -0.1642084658679847
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.6206741496434731
        ow: 0.7840686194232949
    #prateleira itec gabriel
    prateleira_itec:
      px: 1.6100788208670305
      py: -0.280926822372318
      pz: 0.0
      ox: 0.0
      oy: 0.0
      oz: -0.012354080027789436
      ow: 0.9999236854413776
    #prateleira itec edom 
    bottle:
      px: 0.7091632582963708
      py: 0.05500638359559959
      pz: 0.0
      ox: 0.0
      oy: 0.0
      oz: -0.039419223031541176
      ow: 0.9992227603770791
    bottle_object:
      px: 1.9134325086066921
      py: 0.022014862973275408
      pz: 0.9033840149724682
      ox: 0.5794437140284103
      oy: -0.5736114628592116
      oz: 0.4056073707483129
      ow: -0.4131555868142223
    #Simulated Clean Up
    # detect_point1:
    #     px: 2.65309002417596
    #     py: 0.1413974332598916
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.9241319777799488
    #     ow: 0.38207340609432644
    # detect_point2:
    #     px: 1.580048412423603
    #     py: -0.057960625087477236
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.813471442722344
    #     ow: 0.5816048588820663
    # drawer_left:
    #     px: 0.45243142566995323
    #     py: 0.6
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: -0.7071068
    #     ow: 0.7071068
    # drawer_left_place_1:
    #     px: 0.45243142566995323
    #     py: 0
    #     pz: 0.40
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # drawer_top:
    #     px: 0.19428819133805452
    #     py: 0.6
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: -0.7071068
    #     ow: 0.7071068
    # drawer_top_place_1:
    #     px: 0.19428819133805452
    #     py: 0
    #     pz: 0.60
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # drawer_botton:
    #     px: 0.19428819133805452
    #     py: 0.6
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: -0.7071068
    #     ow: 0.7071068
    # drawer_botton_place_1:
    #     px: 0.19428819133805452
    #     py: 0
    #     pz: 0.40
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_a:
    #     px: 1.6766933413571498
    #     py: 0.10861326386830174
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: -0.7071068
    #     ow: 0.7071068
    # tray_a_place_1:
    #     px: 1.55
    #     py: -0.69
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_a_place_2:
    #     px: 1.69
    #     py: -0.69
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_a_place_3:
    #     px: 1.55
    #     py: -0.58
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_a_place_4:
    #     px: 1.69
    #     py: -0.58
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_a_place_5:
    #     px: 1.55
    #     py: -0.47
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_a_place_6:
    #     px: 1.69
    #     py: -0.47
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_b:
    #     px: 1.967001338042723
    #     py: 0.10861326386830174
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: -0.7071068
    #     ow: 0.7071068
    # tray_b_place_1:
    #     px: 1.82
    #     py: -0.69
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_b_place_2:
    #     px: 1.95
    #     py: -0.69
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_b_place_3:
    #     px: 1.82
    #     py: -0.58
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_b_place_4:
    #     px: 1.95
    #     py: -0.58
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_b_place_5:
    #     px: 1.82
    #     py: -0.47
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # tray_b_place_6:
    #     px: 1.95
    #     py: -0.47
    #     pz: 0.45
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # container_a:
    #     px: 1.0919534521660893
    #     py: 0.10861326386830174
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: -0.7071068
    #     ow: 0.7071068
    # container_a_place_1:
    #     px: 1.03
    #     py: -0.51
    #     pz: 0.58
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # container_a_place_2:
    #     px: 1.16
    #     py: -0.51
    #     pz: 0.58
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # container_b:
    #     px: 1.4071946923036748
    #     py: 0.10861326386830174
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: -0.7071068
    #     ow: 0.7071068
    # container_b_place_1:
    #     px: 1.3771946923036748
    #     py: -0.56
    #     pz: 0.54
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # bin_a:
    #     px: 2.374242766808463
    #     py: 0.18
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: -0.7071068
    #     ow: 0.7071068
    # bin_a_place_1:
    #     px: 2.374242766808463
    #     py: -0.54
    #     pz: 0.40
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # bin_b:
    #     px: 2.250688714724289
    #     py: 0.07726537442903898
    #     pz: 0.0
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1
    # bin_b_place_1:
    #     px: 2.90
    #     py: -0.54
    #     pz: 0.40
    #     ox: 0.0
    #     oy: 0.0
    #     oz: 0.0
    #     ow: 1