pose:
  targets:
    observation:
        px: 34.4919
        py: 23.2929
        pz: 0
        ox: 0
        oy: 0
        oz: 0.8730
        ow: 0.4876
    exit:
        px: 38.0448
        py: 25.7673
        pz: 0
        ox: 0
        oy: 0
        oz: -0.1551
        ow: 0.9878
