pose:
  targets:
  # c3 --------------c2
  # |                 |
  # |  cabinet split  |
  # |  on the floor   |
  # |                 |
  # c4 --------------c1
    cabinet_1:
      px: 5.0
      py: 0.0
      pz: 0.0 
      ox: 0.0
      oy: 0.0
      oz: 0.0
      ow: 0.0
    cabinet_2: 
      px: 5.0
      py: 4.0
      pz: 0.0
      ox: 0.0
      oy: 0.0
      oz: 0.0
      ow: 0.0
    cabinet_3:
      px: -1.0
      py: 4.0
      pz: 0.0
      ox: 0.0
      oy: 0.0
      oz: 0.0
      ow: 0.0
    cabinet_4:
      px: -1.0
      py: 0.0
      pz: 0.0
      ox: 0.0
      oy: 0.0
      oz: 0.0
      ow: 0.0





