pose:
  targets:
    #poses de observacao:
    kitchen:
        px: 0.0
        py: 0.0
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 0.0
    living_room:
        px: 0.0
        py: 0.0
        pz: 0.0 
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 0.0
    bedroom:
        px: 0.0 
        py: 0.0
        pz: 0.0 
        ox: 0.0
        oy: 0.0
<<<<<<< HEAD
        oz: 0.0
        ow: 0.0
    bathroom:
        px: 0.0 
        py: 0.0
=======
        oz: 
        ow: 
    kitchen_2:
        px: 3.141406253120765
        py: 5.472461049613243
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7962697038712218
        ow: 0.6049417812457963
    living room_2:
        px: 
        py: 
>>>>>>> feat/gpsr
        pz: 0.0 
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 0.0
