pose:
  targets:
    detect_point1:
        px: 2.65309002417596
        py: 0.1413974332598916
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: 0.9241319777799488
        ow: 0.38207340609432644
    detect_point2:
        px: 1.580048412423603
        py: -0.057960625087477236
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: 0.813471442722344
        ow: 0.5816048588820663
    drawer_left:
        px: 0.41243142566995323
        py: 0.48018787647135597
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7071068
        ow: 0.7071068
    drawer_left_place_1:
        px: 0.41243142566995323
        py: 0.18018787647135597
        pz: 0.40
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    drawer_top:
        px: 0.14428819133805452
        py: 0.48018787647135597
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7071068
        ow: 0.7071068
    drawer_top_place_1:
        px: 0.14428819133805452
        py: 0.18018787647135597
        pz: 0.60
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    drawer_botton:
        px: 0.14428819133805452
        py: 0.48018787647135597
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7071068
        ow: 0.7071068
    drawer_botton_place_1:
        px: 0.14428819133805452
        py: 0.18018787647135597
        pz: 0.40
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_a:
        px: 1.5766933413571498
        py: 0.10861326386830174
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7071068
        ow: 0.7071068
    tray_a_place_1:
        px: 1.45
        py: -0.69
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_a_place_2:
        px: 1.69
        py: -0.69
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_a_place_3:
        px: 1.45
        py: -0.58
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_a_place_4:
        px: 1.69
        py: -0.58
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_a_place_5:
        px: 1.45
        py: -0.47
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_a_place_6:
        px: 1.69
        py: -0.47
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_b:
        px: 1.917001338042723
        py: 0.10861326386830174
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7071068
        ow: 0.7071068
    tray_b_place_1:
        px: 1.79
        py: -0.69
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_b_place_2:
        px: 2.03
        py: -0.69
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_b_place_3:
        px: 1.79
        py: -0.58
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_b_place_4:
        px: 2.03
        py: -0.58
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_b_place_5:
        px: 1.79
        py: -0.47
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    tray_b_place_6:
        px: 2.03
        py: -0.47
        pz: 0.45
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    container_a:
        px: 1.0419534521660893
        py: 0.10861326386830174
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7071068
        ow: 0.7071068
    container_a_place_1:
        px: 1.00
        py: -0.54
        pz: 0.58
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    container_a_place_2:
        px: 1.13
        py: -0.54
        pz: 0.58
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    container_b:
        px: 1.3071946923036748
        py: 0.10861326386830174
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7071068
        ow: 0.7071068
    container_b_place_1:
        px: 1.3071946923036748
        py: -0.54
        pz: 0.54
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    bin_a:
        px: 2.374242766808463
        py: 0.18
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: -0.7071068
        ow: 0.7071068
    bin_a_place_1:
        px: 2.374242766808463
        py: -0.54
        pz: 0.40
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    bin_b:
        px: 2.250688714724289
        py: 0.07726537442903898
        pz: 0.0
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1
    bin_b_place_1:
        px: 2.90
        py: -0.54
        pz: 0.40
        ox: 0.0
        oy: 0.0
        oz: 0.0
        ow: 1